import React from "react"
import Head from "next/head"
import styles from "../styles/Home.module.css"
import { Layout } from "../components/Layout/Layout"
import { request } from "../lib/datocms"
import { FULL_ARTICLE_FRAGMENT, gql, TOPNAV_FRAGMENT } from "../lib/queries"
import { ArticleContent } from "../components/ArticleContent/ArticleContent"

export default function Home({ article, topnav }) {
  return (
    <React.Fragment>
      <Head>
        <title>Klevu documentation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout topnav={topnav}>
        <h1>{article.title}</h1>
        <ArticleContent content={article.content} />
      </Layout>
    </React.Fragment>
  )
}

export async function getStaticProps(context) {
  const req = await request({
    query: FRONTPAGE,
    preview: Boolean(context.preview),
  })
  return {
    props: {
      article: req.article,
      topnav: req.topnav.children,
    },
  }
}

const FRONTPAGE = gql`
  query {
    article(filter: { slug: { eq: "frontpage" } }) {
      ...FullArticle
      children {
        id
        slug
      }
    }

    topnav: article(filter: { slug: { eq: "frontpage" } }) {
      ...TopNav
    }
  }
  ${FULL_ARTICLE_FRAGMENT}
  ${TOPNAV_FRAGMENT}
`
