/* Automatically generated by generateParts.js - Do not modify by hand - Use "npm run generate:parts" to update */
export const parts = {
  "klevu-button": {
    local: ["button-base"],
    exportedcomponents: {},
  },
  "klevu-facet": {
    local: ["facet-heading"],
    exportedcomponents: { "klevu-button": ["button-base"] },
  },
  "klevu-popup": {
    local: ["popup-origin", "popup-content"],
    exportedcomponents: {},
  },
  "klevu-product": {
    local: ["product-image", "product-container", "product-swatch"],
    exportedcomponents: { "klevu-button": ["button-base"] },
  },
  "klevu-product-query": {
    local: [
      "product-query-header",
      "product-query-footer",
      "product-query-feedback",
      "product-query-open-button",
      "product-query-button-icon",
    ],
    exportedcomponents: {
      "klevu-button": ["button-base"],
      "klevu-product-query-popup": [
        "product-query-popup-header",
        "product-query-popup-footer",
        "product-query-popup-feedback",
      ],
      "klevu-popup": ["popup-origin", "popup-content"],
      "klevu-product": ["product-image", "product-container", "product-swatch"],
    },
  },
  "klevu-product-query-popup": {
    local: ["product-query-popup-header", "product-query-popup-footer", "product-query-popup-feedback"],
    exportedcomponents: {
      "klevu-popup": ["popup-origin", "popup-content"],
      "klevu-button": ["button-base"],
      "klevu-product": ["product-image", "product-container", "product-swatch"],
    },
  },
}
