/* Automatically generated by generateParts.js - Do not modify by hand - Use "npm run generate:parts" to update */
export const parts = {
  "klevu-accordion": {
    local: ["accordion-base", "accordion-header", "accordion-content", "accordion-icon"],
    exportedcomponents: {},
  },
  "klevu-badge": {
    local: ["badge-content"],
    exportedcomponents: {},
  },
  "klevu-button": {
    local: ["button-base"],
    exportedcomponents: {},
  },
  "klevu-chat-bubble": {
    local: [
      "chat-bubble-base",
      "chat-bubble-positive-feedback",
      "chat-bubble-negative-feedback",
      "chat-bubble-feedback-reasons",
    ],
    exportedcomponents: { "klevu-button": ["button-base"] },
  },
  "klevu-checkbox": {
    local: ["checkbox-base", "checkbox-box", "checkbox-content"],
    exportedcomponents: {},
  },
  "klevu-chip": {
    local: ["chip-base", "chip-icon", "chip-content"],
    exportedcomponents: {},
  },
  "klevu-facet": {
    local: ["facet-heading"],
    exportedcomponents: {
      "klevu-accordion": ["accordion-base", "accordion-header", "accordion-content", "accordion-icon"],
      "klevu-checkbox": ["checkbox-base", "checkbox-box", "checkbox-content"],
      "klevu-button": ["button-base"],
    },
  },
  "klevu-popup": {
    local: ["popup-origin", "popup-content"],
    exportedcomponents: {},
  },
  "klevu-product": {
    local: ["product-image", "product-container", "product-swatch"],
    exportedcomponents: { "klevu-button": ["button-base"] },
  },
  "klevu-product-query": {
    local: ["product-query-open-button"],
    exportedcomponents: {
      "klevu-button": ["button-base"],
      "klevu-product-query-popup": [
        "product-query-popup-header",
        "product-query-popup-footer",
        "product-query-popup-feedback",
      ],
      "klevu-popup": ["popup-origin", "popup-content"],
      "klevu-chat-bubble": [
        "chat-bubble-base",
        "chat-bubble-positive-feedback",
        "chat-bubble-negative-feedback",
        "chat-bubble-feedback-reasons",
      ],
      "klevu-product": ["product-image", "product-container", "product-swatch"],
    },
  },
  "klevu-product-query-popup": {
    local: ["product-query-popup-header", "product-query-popup-footer", "product-query-popup-feedback"],
    exportedcomponents: {
      "klevu-popup": ["popup-origin", "popup-content"],
      "klevu-button": ["button-base"],
      "klevu-chat-bubble": [
        "chat-bubble-base",
        "chat-bubble-positive-feedback",
        "chat-bubble-negative-feedback",
        "chat-bubble-feedback-reasons",
      ],
      "klevu-product": ["product-image", "product-container", "product-swatch"],
    },
  },
}
