/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { KlevuRecord } from "@klevu/core";
export namespace Components {
    interface KlevuProduct {
        "product": KlevuRecord;
    }
}
declare global {
    interface HTMLKlevuProductElement extends Components.KlevuProduct, HTMLStencilElement {
    }
    var HTMLKlevuProductElement: {
        prototype: HTMLKlevuProductElement;
        new (): HTMLKlevuProductElement;
    };
    interface HTMLElementTagNameMap {
        "klevu-product": HTMLKlevuProductElement;
    }
}
declare namespace LocalJSX {
    interface KlevuProduct {
        "product"?: KlevuRecord;
    }
    interface IntrinsicElements {
        "klevu-product": KlevuProduct;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "klevu-product": LocalJSX.KlevuProduct & JSXBase.HTMLAttributes<HTMLKlevuProductElement>;
        }
    }
}
