# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run @klevu/core tests

on:
  push:
    branches: [master]
    paths:
      - "packages/klevu-core/src/**"
  pull_request:
    branches: [master]
    paths:
      - "packages/klevu-core/src/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/klevu-core
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: packages/klevu-core/package-lock.json
      - run: npm install
      - run: npm test
