name: Update versions and release UI packages

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Which update to do
        options:
          - major
          - minor
          - patch

jobs:
  deploy:
    name: Release
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Make Release
        id: release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd utils
          npm install --force
          node ./update-klevu-ui.js --type ${{ inputs.type }} --no-otp

      - name: Print
        run: echo ${{steps.release.outputs.version}}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Automatic @klevu/ui release"
          branch: release/ui-${{steps.release.outputs.version}}
          title: "@klevu/ui release ${{steps.release.outputs.version}}"
          body: |
            This is automatic update of package versions. 
            NPM release has been already made and this is just update to repository.
