name: Update versions and release UI packages

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Which update to do
        options:
          - major
          - minor
          - patch

jobs:
  deploy:
    name: Release
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Make Release
        id: make-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd utils
          npm install
          node ./update-klevu-ui.js --type ${{ inputs.type }} --dry-run
