name: Update versions and release UI packages

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Which update to do
        options:
          - major
          - minor
          - patch

jobs:
  deploy:
    name: Release
    runs-on: ubuntu-latest
    environment: production

    outputs:
      version: ${{ steps.make-release.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Make Release
        id: make-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd utils
          npm install
          node ./update-klevu-ui.js --type ${{ inputs.type }} --dry-run

      - name: Print
        run: echo ${{needs.deploy.outputs.version}}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Automatic @klevu/ui release"
          committer: GitHub action [bot] <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: release/ui-${{ needs.deploy.outputs.version }}
          title: "@klevu/ui release ${{ needs.deploy.outputs.version }}"
          body: |
            This is automatic update of package versions. 
            NPM release has been already made and this is just update to repository.
