name: Publish Storybook

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/storybook-release.yml"
      - "packages/klevu-ui/src/**"
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/klevu-ui
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run build-storybook
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_STORYBOOK_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_STORYBOOK_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Copy files with the AWS CLI
        run: |
          aws s3 sync storybook-static/ s3://storybook.klevu.com
